# Website settings
baseurl: "/"
url: "http://unnamed-idea.github.io"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    photos: "/photos"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "talha korkmaz"
slogan: "applied data science, positive psychology and whatnot"
description: "My personal blog on which I share my thoughts and notes."
thumbnail_path: "profile-photos/blog-author-medium.jpg"
website_repo_url: "https://github.com/unnamed-idea/unnamed-idea.github.io"

# URLs
contact_urls:
  
  linkedin:
    url: "https://www.linkedin.com/in/talha-korkmaz-76b7346a/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/unnamed-idea"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:mtk991@gmail.com"
    label: "Email"
    value: "mtk991@gmail.com"
    icon: "envelope-square"
  twitter:
    url: "https://twitter.com/unnamedidea"
    label: "Twitter"
    icon: "twitter-square"
    username: "@unnamedidea"
  gitlab:
    url: "https://gitlab.com/mtk991"
    label: "GitLab"
    icon: "github-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Istanbul'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
markdown: kramdown 
